### ISSUE TITLE
Bower published 1.7.5 today, now grunt-bower-install-simple is failing

### ISSUE THREAD

**Issue by mstuart** [rse/grunt-bower-install-simple#19]
```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'bower/lib/renderers/StandardRenderer'
Warning: Task "test" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
```

**Comment by mstuart** [comment]
https://github.com/rse/grunt-bower-install-simple/blob/master/tasks/grunt-bower-install-simple.js#L32 is reaching into `bower/lib/renderers/StandardRenderer`.  I think that's missing with bower@1.7.5 which was published an hour ago :(

**Comment by sam-taylor-dt** [comment]
yup - i'm seeing the same issue

**Comment by 2ndalpha** [comment]
+1

**Comment by derTobsch** [comment]
+1

**Comment by derTobsch** [comment]
I added a pull request #21 which will fix this issue with a proper bower version (1.7.1).

**Comment by derTobsch** [comment]
https://github.com/bower/bower/issues/2160

Some Information how to access the renderers

**Comment by andricDu** [comment]
While i was debugging this i discovered that `bower/lib/renderers/` -> `bower/lib/lib/renderers/`

**Comment by davewhiteley** [comment]
Thank you @derTobsch

**Comment by rse** [comment]
With the latest Bower 1.7.7 the problem seems to be already fixed. I've published grunt-bower-install-simple 1.2.1 which now uses Bower 1.7.7.

**Comment by sanx** [comment]
I'm still having the same issue, and with `grunt-bower-install-simple` 1.2.1 and `bower` 1.7.7

**Comment by derTobsch** [comment]
@rse please use proper versions, else there is a good chance that this package will break in future when the dependencies will upgrade with breaking changes. Especially because you are using private apis of the dependencies.
